# Generated by Django 6.0.5 on 2026-05-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.usuario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='usuarios.local')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('cliente', 'local')},
            },
        ),
    ]
