# Generated by Django 6.0.5 on 2026-05-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='reservas_participadas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_recibidas', to='usuarios.usuario')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_enviadas', to='usuarios.usuario')),
            ],
            options={
                'unique_together': {('remitente', 'destinatario')},
            },
        ),
    ]
