# Generated by Django 6.0.5 on 2026-05-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_reserva_participantes_reserva_ticket_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='telefonos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
