# Generated by Django 6.0.5 on 2026-05-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_reserva_pendiente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amistad',
        ),
    ]
