# Generated by Django 6.0.5 on 2026-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_local_qr_code_local_qr_expiry_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
    ]
