# Generated by Django 6.0.5 on 2026-05-25 08:43

from django.db import migrations, models


CREATE_VIEW = """
CREATE OR REPLACE VIEW v_ingresos_mensuales AS
SELECT
    l.dueno_id,
    to_char(p.created_at, 'YYYY-MM') AS mes,
    COUNT(r.id)::int AS total_reservas,
    COALESCE(SUM(p.monto) FILTER (WHERE p.estado = 'pagado'), 0) AS ingresos,
    COALESCE(SUM(p.monto) FILTER (WHERE p.estado = 'reembolsado'), 0) AS reembolsos
FROM usuarios_pago p
JOIN usuarios_reserva r ON r.id = p.reserva_id
JOIN usuarios_cancha c ON c.id = r.cancha_id
JOIN usuarios_local l ON l.id = c.local_id
GROUP BY l.dueno_id, to_char(p.created_at, 'YYYY-MM')
ORDER BY l.dueno_id, mes DESC;
"""

DROP_VIEW = "DROP VIEW IF EXISTS v_ingresos_mensuales;"


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_reserva_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de Pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], db_index=True, default='confirmada', max_length=20),
        ),
        migrations.RunSQL(CREATE_VIEW, DROP_VIEW),
    ]
